file_data = {
    'RData_basic': {'about':'RData files are used by the statistical programming language R. They are used to store user created objects and functions.',
        'download':'ffc.RData',
        'ext':'.RData',
        'icon':'code.png',
        'file_kind':['program data'],
        'name':'Stored R Object',
        'tags': ['code'],
        'conversions':[''],
        'wiki':'R_(programming_language)',
        'official_website':'http://www.r-project.org/',
        'popularity':'low', 'usability':'high'},
    'R_basic': {'about':'R files are used by the statistical programming language R. Code is written and stored in R files.',
        'download':'ffc.R',
        'ext':'.R',
        'icon':'code.png',
        'file_kind':['code'],
        'name':'R programming language',
        'tags': ['code'],
        'conversions':[''],
        'wiki':'R_(programming_language)',
        'official_website':'http://www.r-project.org/',
        'popularity':'high', 'usability':'high'},
    'bmp_basic': {'about':'BMP are used to store 2D image data.',
        'download':'ffc.bmp',
        'ext':'.bmp',
        'icon':'image.png',
        'file_kind':['image'],
        'name':'Windows bitmap',
        'tags': ['images'],
        'conversions':['gif_basic','jpg_basic','png_basic','tiff_basic','pdf_basic'],
        'wiki':'BMP_file_format',
        'official_website':'',
        'popularity':'high', 'usability':'high'},
    'css_basic': {'about':'CSS (Cascading Style Sheets) are used to style HTML and store the code that modifies html.',
        'download':'ffc.css',
        'ext':'.css',
        'icon':'code.png',
        'file_kind':['web'],
        'name':'css',
        'tags': ['code'],
        'conversions':[''],
        'wiki':'css',
        'official_website':'',
        'popularity':'high', 'usability':'high'},
    'csv_basic': {'about':'Cvs files are used to store values which are separated by commas.',
        'download':'ffc.csv',
        'ext':'.csv',
        'icon':'data.png',
        'file_kind':['data frame'],
        'name':'Comma-Separated Values',
        'tags': ['data'],
        'conversions':['xlsx_basic','txt_basic','xls.basic','ods_basic'],
        'wiki':'Comma-separated_values',
        'official_website':'',
        'popularity':'high', 'usability':'high'},
    'dbf_basic': {'about':'Dbf files are used to store structured data.',
        'download':'ffc.dbf',
        'ext':'.dbf',
        'icon':'data.png',
        'file_kind':['data frame'],
        'name':'DataBase File',
        'tags': ['data'],
        'conversions':[''],
        'wiki':'DBase',
        'official_website':'www.dbase.com',
        'popularity':'low', 'usability':'medium'},
    'dcm_basic': {'about':'Dcm files are a standard format used for medical imaging.',
        'download':'ffc.dcm',
        'ext':'.dcm',
        'icon':'image.png',
        'file_kind':['image'],
        'name':'Digital Imaging and Communications in Medicine',
        'tags': ['image'],
        'conversions':[''],
        'wiki':'Digital_Imaging_and_Communications_in_Medicine', 'official_website':'http://dicom.nema.org/', 'popularity':'high', 'usability':'low'},
    'dif_basic': {'about':'Dif files are an interchange format used to send and receive spreadsheets between programs.',
        'download':'ffc.dif',
        'ext':'.dif',
        'icon':'data.png',
        'file_kind':['data frame'],
        'name':'Data Interchange Format',
        'tags': ['data'],
        'conversions':[''],
        'wiki':'Data_Interchange_Format', 'official_website':'', 'popularity':'low', 'usability':'low'},
    'doc_6': {'about':'Doc files are generally used to store text but can also contain images or tables. Doc 6.0 is a version compatibale with Word 6.0.',
        'download':'ffc_6.doc',
        'ext':'.doc',
        'icon':'text.png',
        'file_kind':['document'],
        'name':'Microsoft 6.0 Document',
        'tags': ['text','Microsoft', 'document'],
        'conversions':['docx_basic','pdf_basic'],
        'wiki':'Doc_(computing)',
        'official_website':'http://www.microsoft.com/',
        'popularity':'high', 'usability':'medium'},
    'doc_95': {'about':'Doc files are generally used to store text but can also contain images or tables. Doc 95 is a version compatibale with Word 95.',
        'download':'ffc_95.doc',
        'ext':'.doc',
        'icon':'text.png',
        'file_kind':['document'],
        'name':'Microsoft 95 Document',
        'tags': ['text','Microsoft','document'],
        'conversions':['docx_basic','pdf_basic'],
        'wiki':'Doc_(computing)',
        'official_website':'http://www.microsoft.com/',
        'popularity':'high', 'usability':'medium'},
    'doc_97_2000_xp': {'about':'Doc files are generally used to store text but can also contain images or tables. Doc 97, 2000, and XP is a version compatibale with Word 97, 2000, and XP.',
        'download':'ffc_97_2000_xp.doc',
        'ext':'.doc',
        'icon':'text.png',
        'file_kind':['document'],
        'name':'Microsoft 97, 2000, and XP Document',
        'tags': ['text','Microsoft', 'document'],
        'conversions':['docx_basic','pdf_basic'],
        'wiki':'Doc_(computing)', 'official_website':'http://www.microsoft.com/', 'popularity':'high', 'usability':'medium'},
    'docx_basic': {'about':'Docx files are generally used to store text, but can also contain images or tables. Docx is an XML version of earlier doc formats.',
        'download':'ffc.docx',
        'ext':'.docx',
        'icon':'text.png',
        'file_kind':['document'],
        'name':'Open XML Microsoft document',
        'tags': ['text','Microsoft', 'document'],
        'conversions':['doc97_2000_xp','pdf_basic'],
        'wiki':'Docx', 'official_website':'http://www.microsoft.com/', 'popularity':'high', 'usability':'high'},
    'dta_12': {'about':'',
        'download':'ffc_12.dta',
        'ext':'.dta',
        'icon':'data.png',
        'file_kind':['data frame'],
        'name':'STATA Data Version 12',
        'tags': ['data'],
        'conversions':['csv_basic, xlsx_basic'],
        'wiki':'Stata', 'official_website':'', 'popularity':'low', 'usability':'low'},
    'dta_13': {'about':'',
        'download':'ffc_13.dta',
        'ext':'.dta',
        'icon':'data.png',
        'file_kind':['data frame'],
        'name':'STATA Data Version 13',
        'tags': ['data'],
        'conversions':['csv_basic, xlsx_basic'],
        'wiki':'Stata', 'official_website':'', 'popularity':'low', 'usability':'low'},
    'gif_basic': {'about':'',
        'download':'ffc.gif',
        'ext':'.gif',
        'icon':'image.png',
        'file_kind':['image'],
        'name':'Graphics Interchange Format',
        'tags': ['images'],
        'conversions':['jpg_basic','png_basic','bmp_basic','tiff_basic','pdf_basic'],
        'wiki':'Gif', 'official_website':'', 'popularity':'high', 'usability':'high'},
    'html_basic': {'about':'',
        'download':'fcc.html',
        'ext':'.html',
        'icon':'code.png',
        'file_kind':[''],
        'name':'HyperText Markup Language',
        'tags': ['code'],
        'conversions':[''],
        'wiki':'HTML', 'official_website':'', 'popularity':'high', 'usability':'high'},
    'iff_basic': {'about':'',
        'download':'ffc.iff',
        'ext':'.iff',
        'icon':'image.png',
        'file_kind':['image'],
        'name':'Interchange File Format',
        'tags': ['image'],
        'conversions':[''],
        'wiki':'Interchange_File_Format', 'official_website':'', 'popularity':'low', 'usability':'low'},
    'ipynb_basic': {'about':'',
        'download':'ffc.ipynb',
        'ext':'.ipynb',
        'icon':'code.png',
        'file_kind':['program data'],
        'name':'IPython Notebook',
        'tags': ['code'],
        'conversions':[''],
        'wiki':'IPython', 'official_website':'', 'popularity':'medium', 'usability':'medium'},
    'jpg_basic': {'about':'',
        'download':'ffc.jpg',
        'ext':'.jpg, jpeg',
        'icon':'image.png',
        'file_kind':['image'],
        'name':'Joint Photographic Experts Group',
        'tags': ['images'],
        'conversions':['gif_basic','png_basic','bmp_basic','tiff_basic','pdf_basic'],
        'wiki':'JPEG', 'official_website':'', 'popularity':'high', 'usability':'high'},
    'js_basic': {'about':'.js files are used to run JavaScript code. JavaScript code is stored in .js files',
        'download':'fcc.js',
        'ext':'.js',
        'icon':'code.png',
        'file_kind':['code'],
        'name':'JavaScript programming language',
        'tags': ['code'],
        'conversions':[''],
        'wiki':'Javascript', 'official_website':'', 'popularity':'high', 'usability':'high'},
    'json_basic': {'about':'',
        'download':'ffc.json',
        'ext':'.json',
        'icon':'data.png',
        'file_kind':['data'],
        'name':'JavaScript Object Notation',
        'tags': ['data','code'],
        'conversions':[''],
        'wiki':'JSON', 'official_website':'', 'popularity':'high', 'usability':'high'},
    'mako_basic': {'about':'',
        'download':'None!',
        'ext':'.mako',
        'icon':'code.png',
        'file_kind':['web'],
        'name':'Mako Python template engine',
        'tags': ['code'],
        'conversions':[''],
        'wiki':'Mako_(template_engine)', 'official_website':'', 'popularity':'low', 'usability':'high'},
    # 'mov_basic': {'about':'',
    #     'download':'ffc.',
    #     'ext':'.mov',
    #     'icon':'image.png',
    #     'file_kind':[''],
    #     'name':'Quicktime movie',
    #     'tags': ['image'],
    #     'conversions':[''],
    #     'wiki':'', 'official_website':'', 'popularity':'', 'usability':''},
    # 'mp3_basic': {'about':'',
    #     'download':'ffc.',
    #     'ext':'.mp3',
    #     'icon':'audio.png',
    #     'file_kind':[''],
    #     'name':'MP3 Audio',
    #     'tags': ['audio'],
    #     'conversions':[''],
    #     'wiki':'', 'official_website':'', 'popularity':'', 'usability':''},
    # 'mpg_basic': {'about':'',
    #     'download':'ffc.',
    #     'ext':'.mpg',
    #     'icon':'movie.png',
    #     'file_kind':[''],
    #     'name':'MPEG-1 Video',
    #     'tags': ['movie','video'],
    #     'conversions':[''],
    #     'wiki':'', 'official_website':'', 'popularity':'', 'usability':''},
    'ods_basic': {'about':'',
        'download':'ffc.ods',
        'ext':'.ods',
        'icon':'data.png',
        'file_kind':['spreadsheet'],
        'name':'Open Office Spreadsheet',
        'tags': ['data'],
        'conversions':['xlsx_basic', 'csv_basic'],
        'wiki':'OpenDocument', 'official_website':'', 'popularity':'medium', 'usability':'high'},
    'odt_basic': {'about':'',
        'download':'ffc.odt',
        'ext':'.odt',
        'icon':'text.png',
        'file_kind':['document'],
        'name':'Open Office Text Document',
        'tags': ['text'],
        'conversions':['docx_basic','pdf_basic'],
        'wiki':'OpenDocument', 'official_website':'', 'popularity':'medium', 'usability':'high'},
    'ots_basic': {'about':'',
        'download':'ffc.odt',
        'ext':'.ots',
        'icon':'data.png',
        'file_kind':['template'],
        'name':'Open Office Spreadsheet Template',
        'tags': ['data'],
        'conversions':[''],
        'wiki':'OpenDocument', 'official_website':'', 'popularity':'low', 'usability':'medium'},
    'ott_basic': {'about':'',
        'download':'ffc.ott',
        'ext':'.ott',
        'icon':'text.png',
        'file_kind':['template'],
        'name':'Open Office Text Template',
        'tags': ['text'],
        'conversions':[''],
        'wiki':'OpenDocument', 'official_website':'', 'popularity':'low', 'usability':'medium'},
    'pbm_basic': {'about':'',
        'download':'ffc.pbm',
        'ext':'.pbm',
        'icon':'image.png',
        'file_kind':['image'],
        'name':'Netpbm format',
        'tags': ['image'],
        'conversions':[''],
        'wiki':'Netpbm_format', 'official_website':'', 'popularity':'low', 'usability':'low'},
    'pct_basic': {'about':'',
        'download':'ffc.pct',
        'ext':'.pict, .pic, .pct',
        'icon':'image.png',
        'file_kind':['image'],
        'name':'Macintosh picture metafile',
        'tags': ['image'],
        'conversions':[''],
        'wiki':'PICT', 'official_website':'', 'popularity':'low', 'usability':'medium'},
    'pcx_basic': {'about':'',
        'download':'ffc.pcx',
        'ext':'.pcx',
        'icon':'image.png',
        'file_kind':['image'],
        'name':'Personal Computer Exchange',
        'tags': ['image'],
        'conversions':[''],
        'wiki':'PCX', 'official_website':'', 'popularity':'low', 'usability':'low'},
    'pdb_palm': {'about':'',
        'download':'ffc_palm.pdb',
        'ext':'.pdb',
        'icon':'image.png',
        'file_kind':['document'],
        'name':'AportisDoc (Palm)',
        'tags': ['text'],
        'conversions':[''],
        'wiki':'PDB_(Palm_OS)', 'official_website':'', 'popularity':'low', 'usability':'low'},
    'pdb_protein': {'about':'',
        'download':'1mbs.pdb',
        'ext':'.pdb',
        'icon':'molecule.png',
        'file_kind':['data'],
        'name':'Protein Data Bank File',
        'tags': ['science'],
        'conversions':[''],
        'wiki':'Protein_Data_Bank_(file_format)', 'official_website':'', 'popularity':'low', 'usability':'low'},
    'pdf_basic': {'about':'',
        'download':'ffc.pdf',
        'ext':'.pdf',
        'icon':'text.png',
        'file_kind':['document'],
        'name':'Portable Document Format',
        'tags': ['text'],
        'conversions':[''],
        'wiki':'Pdf', 'official_website':'', 'popularity':'high', 'usability':'medium'},
    'png_basic': {'about':'',
        'download':'ffc.png',
        'ext':'.png',
        'icon':'image.png',
        'file_kind':['image'],
        'name':'Portable Network Graphics',
        'tags': ['images'],
        'conversions':['gif_basic','jpg_basic','bmp_basic','tiff_basic','pdf_basic'],
        'wiki':'Portable_Network_Graphics', 'official_website':'', 'popularity':'high', 'usability':'high'},
    'ppt_basic': {'about':'',
        'download':'ffc.ppt',
        'ext':'.ppt',
        'icon':'image.png',
        'file_kind':['presentation'],
        'name':'Microsoft PowerPoint',
        'tags': ['image','Microsoft'],
        'conversions':[''],
        'wiki':'Microsoft_PowerPoint#File_formats', 'official_website':'', 'popularity':'medium', 'usability':'low'},
    'pptx_basic': {'about':'',
        'download':'ffc.pptx',
        'ext':'.pptx',
        'icon':'presentation.png',
        'file_kind':['presentation'],
        'name':'Open XML Microsoft PowerPoint',
        'tags': ['image','Microsoft'],
        'conversions':[''],
        'wiki':'Microsoft_PowerPoint#File_formats', 'official_website':'', 'popularity':'high', 'usability':'medium'},
    'psb_basic': {'about':'',
        'download':'ffc.psb',
        'ext':'.psb',
        'icon':'image.png',
        'file_kind':['image'],
        'name':'Photoshop file',
        'tags': ['image'],
        'conversions':[''],
        'wiki':'Photoshop', 'official_website':'', 'popularity':'high', 'usability':'low'},
    'psd_basic': {'about':'',
        'download':'ffc.psd',
        'ext':'.psd',
        'icon':'image.png',
        'file_kind':[''],
        'name':'Photoshop document',
        'tags': ['image'],
        'conversions':[''],
        'wiki':'Adobe_Photoshop#File_format', 'official_website':'', 'popularity':'high', 'usability':'low'},
    'psw_basic': {'about':'',
        'download':'ffc.psw',
        'ext':'.psw',
        'icon':'text.png',
        'file_kind':['document'],
        'name':'Pocket Word',
        'tags': ['text'],
        'conversions':[''],
        'wiki':'Microsoft_Office_Mobile', 'official_website':'', 'popularity':'low', 'usability':'low'},
    'pxr_basic': {'about':'',
        'download':'ffc.pxr',
        'ext':'.pxr',
        'icon':'image.png',
        'file_kind':['image'],
        'name':'Pixar Image Computer',
        'tags': ['image'],
        'conversions':[''],
        'wiki':'Pixar_Image_Computer', 'official_website':'', 'popularity':'low', 'usability':'low'},
    'python_basic': {'about':'',
        'download':'ffc.py',
        'ext':'.py',
        'icon':'code.png',
        'file_kind':['code'],
        'name':'python',
        'tags': ['code'],
        'conversions':[''],
        'wiki':'python', 'official_website':'', 'popularity':'high', 'usability':'high'},
    'r_basic': {'about':'',
        'download':'ffc.r',
        'ext':'.r',
        'icon':'code.png',
        'file_kind':['code'],
        'name':'r',
        'tags': ['code'],
        'conversions':[''],
        'wiki':'r', 'official_website':'', 'popularity':'high', 'usability':'high'},
    'raw_ps': {'about':'',
        'download':'ffc.raw',
        'ext':'.raw',
        'icon':'image.png',
        'file_kind':['image'],
        'name':'Photoshop Raw File',
        'tags': ['image'],
        'conversions':[''],
        'wiki':'', 'official_website':'', 'popularity':'medium', 'usability':'low'},
    'rtf_basic': {'about':'',
        'download':'ffc.rtf',
        'ext':'.rtf',
        'icon':'text.png',
        'file_kind':['text'],
        'name':'Rich Text Format',
        'tags': ['text'],
        'conversions':[''],
        'wiki':'Rich_Text_Format', 'official_website':'', 'popularity':'high', 'usability':'high'},
    # 'sass_basic': {'about':'',
    #     'download':'ffc.sass',
    #     'ext':'.sass',
    #     'icon':'code.png',
    #     'file_kind':['program data'],
    #     'name':'sass',
    #     'tags': ['code'],
    #     'conversions':[''],
    #     'wiki':'sass', 'official_website':'', 'popularity':'low', 'usability':'low'},
    'sav_basic': {'about':'',
        'download':'ffc.sav',
        'ext':'.sav',
        'icon':'data.png',
        'file_kind':['data frame'],
        'name':'SPSS Data',
        'tags': ['data'],
        'conversions':[''],
        'wiki':'Spss', 'official_website':'', 'popularity':'medium', 'usability':'low'},
    'slk_basic': {'about':'',
        'download':'ffc.slk',
        'ext':'.slk',
        'icon':'data.png',
        'file_kind':['data'],
        'name':'SYmbolic LinK',
        'tags': ['data'],
        'conversions':[''],
        'wiki':'SYmbolic_LinK_(SYLK)', 'official_website':'', 'popularity':'low', 'usability':'high'},
    'spv_basic': {'about':'',
        'download':'ffc.spv',
        'ext':'.spv',
        'icon':'data.png',
        'file_kind':['program data'],
        'name':'SPSS Output File',
        'tags': ['data'],
        'conversions':[''],
        'wiki':'Spss', 'official_website':'', 'popularity':'low', 'usability':'low'},
    'stc_basic': {'about':'',
        'download':'ffc.stc',
        'ext':'.stc',
        'icon':'data.png',
        'file_kind':['template'],
        'name':'Open Office XML Spreadsheet Template',
        'tags': ['data'],
        'conversions':[''],
        'wiki':'OpenOffice.org_XML', 'official_website':'', 'popularity':'low', 'usability':'medium'},
    'stw_basic': {'about':'',
        'download':'ffc.stw',
        'ext':'.stw',
        'icon':'text.png',
        'file_kind':['template'],
        'name':'Open Office XML Text Template',
        'tags': ['image'],
        'conversions':[''],
        'wiki':'OpenOffice.org_XML', 'official_website':'', 'popularity':'low', 'usability':'medium'},
    'svg_basic': {'about':'',
        'download':'ffc.svg',
        'ext':'.svg',
        'icon':'image.png',
        'file_kind':['image'],
        'name':'Scalable Vector Graphics',
        'tags': ['images'],
        'conversions':[''],
        'wiki':'Svg', 'official_website':'', 'popularity':'high', 'usability':'high'},
    'sxc_basic': {'about':'',
        'download':'ffc.sxc',
        'ext':'.sxc',
        'icon':'data.png',
        'file_kind':['spreadsheet'],
        'name':'Open Office XML Spreadsheet',
        'tags': ['data'],
        'conversions':[''],
        'wiki':'OpenOffice.org_XML', 'official_website':'', 'popularity':'low', 'usability':'medium'},
    'sxw_basic': {'about':'',
        'download':'ffc.sxw',
        'ext':'.sxw',
        'icon':'text.png',
        'file_kind':['document'],
        'name':'Open Office XML Text Document',
        'tags': ['image'],
        'conversions':[''],
        'wiki':'OpenOffice.org_XML', 'official_website':'', 'popularity':'low', 'usability':'medium'},
    'tga_basic': {'about':'',
        'download':'ffc.tga',
        'ext':'.tga',
        'icon':'image.png',
        'file_kind':['image'],
        'name':'Truevision TGA',
        'tags': ['image'],
        'conversions':[''],
        'wiki':'Truevision_TGA', 'official_website':'', 'popularity':'low', 'usability':'high'},
    'tiff_basic': {'about':'',
        'download':'ffc.tif',
        'ext':'.tiff',
        'icon':'image.png',
        'file_kind':['image'],
        'name':'Tagged Image File Format',
        'tags': ['images'],
        'conversions':['gif_basic','png_basic','bmp_basic','jpg_basic','pdf_basic'],
        'wiki':'Tagged_Image_File_Format', 'official_website':'', 'popularity':'medium', 'usability':'high'},
    'txt_basic': {'about':'',
        'download':'ffc.txt',
        'ext':'.txt',
        'icon':'text.png',
        'file_kind':['text'],
        'name':'Text File',
        'tags': ['text'],
        'conversions':[''],
        'wiki':'Text_file', 'official_website':'', 'popularity':'high', 'usability':'high'},
    'txt_utf-8': {'about':'',
        'download':'ffc_utf-8.txt',
        'ext':'.txt',
        'icon':'text.png',
        'file_kind':['text'],
        'name':'Text File encoded as utf-8',
        'tags': ['text'],
        'conversions':[''],
        'wiki':'Text_file', 'official_website':'', 'popularity':'high', 'usability':'high'},
    'uos_1': {'about':'',
        'download':'ffc_1.uos',
        'ext':'.uos',
        'icon':'data.png',
        'file_kind':['spreadsheet'],
        'name':'Uniform Office Format Spreadsheet',
        'tags': ['data'],
        'conversions':[''],
        'wiki':'Uniform_Office_Format', 'official_website':'', 'popularity':'low', 'usability':'medium'},
    'uos_2': {'about':'',
        'download':'ffc_2.uos',
        'ext':'.uos',
        'icon':'data.png',
        'file_kind':['spreadsheet'],
        'name':'Uniform Office Format 2 Spreadsheetp',
        'tags': ['data'],
        'conversions':[''],
        'wiki':'Uniform_Office_Format', 'official_website':'', 'popularity':'low', 'usability':'medium'},
    'uot_1': {'about':'',
        'download':'ffc_1.uot',
        'ext':'.uot',
        'icon':'text.png',
        'file_kind':['text'],
        'name':'Uniform Office Format Text',
        'tags': ['text'],
        'conversions':[''],
        'wiki':'Uniform_Office_Format', 'official_website':'', 'popularity':'low', 'usability':'medium'},
    'uot_2': {'about':'',
        'download':'ffc_2.uot',
        'ext':'.uot',
        'icon':'text.png',
        'file_kind':['text'],
        'name':'Uniform Office Format 2 Text',
        'tags': ['text'],
        'conversions':[''],
        'wiki':'Uniform_Office_Format', 'official_website':'', 'popularity':'low', 'usability':'medium'},
    # 'wavs_basic': {'about':'',
    #     'download':'ffc.',
    #     'ext':'.wav',
    #     'icon':'audio.png',
    #     'file_kind':[''],
    #     'name':'Waveform Audio Format',
    #     'tags': ['image'],
    #     'conversions':[''],
    #     'wiki':'', 'official_website':'', 'popularity':'', 'usability':''},
    # 'wma_basic': {'about':'',
    #     'download':'ffc.',
    #     'ext':'.wma',
    #     'icon':'image.png',
    #     'file_kind':[''],
    #     'name':'Windows Media Audio',
    #     'tags': ['image'],
    #     'conversions':[''],
    #     'wiki':'', 'official_website':'', 'popularity':'', 'usability':''},
    # 'wmv_basic': {'about':'',
    #     'download':'ffc.',
    #     'ext':'.wmv',
    #     'icon':'image.png',
    #     'file_kind':[''],
    #     'name':'Windows Media Video',
    #     'tags': ['movie','video'],
    #     'conversions':[''],
    #     'wiki':'', 'official_website':'', 'popularity':'', 'usability':''},
    'xls_basic': {'about':'',
        'download':'ffc.xls',
        'ext':'.xls',
        'icon':'data.png',
        'file_kind':['spreadsheet'],
        'name':'Excel Binary',
        'tags': ['data','Microsoft'],
        'conversions':[''],
        'wiki':'Microsoft_Excel_file_format', 'official_website':'', 'popularity':'high', 'usability':'low'},
    'xlsx_basic': {'about':'',
        'download':'ffc.xlsx',
        'ext':'.xlsx',
        'icon':'data.png',
        'file_kind':['spreadsheet'],
        'name':'Open XML Microsoft spreadsheet',
        'tags': ['data','Microsoft'],
        'conversions':['csv_basic'],
        'wiki':'XLSX', 'official_website':'', 'popularity':'high', 'usability':'medium'},
    'xml_basic': {'about':'',
        'download':'ffc.xml',
        'ext':'.xml',
        'icon':'code.png',
        'file_kind':[''],
        'name':'xml',
        'tags': ['code'],
        'conversions':[''],
        'wiki':'xml', 'official_website':'', 'popularity':'high', 'usability':'high'},
    'xml_docbook': {'about':'',
        'download':'ffc_docbook.xml',
        'ext':'.xml',
        'icon':'text.png',
        'file_kind':['document'],
        'name':'XML Docbook',
        'tags': ['text'],
        'conversions':[''],
        'wiki':'DocBook', 'official_website':'', 'popularity':'low', 'usability':'medium'},
    'xml_word_2003': {'about':'',
        'download':'ffc_word_2003.xml',
        'ext':'.xml',
        'icon':'text.png',
        'file_kind':['document'],
        'name':'Microsoft Word 2003 XML',
        'tags': ['text','Microsoft'],
        'conversions':[''],
        'wiki':'Microsoft_Office_XML_formats', 'official_website':'', 'popularity':'low', 'usability':'medium'},
}